---
title: "Final project - Figure skating and Quads"
---

**Self-Introduction**

As a figure skater, I have always been interested in the competitive scene. I have followed and attended many competitions over the years which allowed me to notice a shift in sport with the prominence of quadruple jumps in single skating. Quadruple jumps have become a standard in Men's figure skating and even have made it into the Women's discipline which was unprecedented before.

**Data set**

I will be utilizing a comprehensive dataset encompassing the outcomes of various Olympic events. This dataset will serve as a foundation for identifying medalists and assessing their scores. By doing so, I aim to draw comparisons between athletes who executed quadruple jumps in their routines and those who did not. This analysis will provide insights into the impact of quadruple jumps on overall scores, thereby aiding in the determination of their significance within the sport.

```{r, eval=TRUE, echo=TRUE}
library(tidyverse)
olympic_results <- read.csv("olympic_results.csv")
fs_results <- olympic_results[olympic_results$discipline_title == "Figure skating",
                              ]
print(fs_results)
```
